---
- name: Assert Input params
  ansible.builtin.assert:
    that:
      - resource_id is defined and resource_id | length > 0
      - service_id is defined

- name: Remove service from consul node
  ansible.builtin.uri:
    url: "{{consul_url}}/v1/catalog/deregister"
    method: PUT
    body_format: json
    body:
      NODE: "{{ resource_id }}"
      ServiceID: "{{ service_id }}"
    headers:
      Authorization: "Bearer {{ consul_token }}"